# Generated by Django 3.0.6 on 2020-05-08 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriculant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('pid', models.CharField(blank=True, help_text='Personal Identifier Number', max_length=256, null=True, verbose_name='PID')),
                ('gender', models.CharField(choices=[('L', 'Male'), ('P', 'Female')], default='L', max_length=1, verbose_name='gender')),
                ('date_of_birth', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date of birth')),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True, verbose_name='place of birth')),
                ('privacy', models.CharField(choices=[('anyone', 'Anyone'), ('users', 'All Users'), ('friends', 'All Friends'), ('students', 'All Students'), ('teachers', 'All Teachers'), ('employees', 'All Employees'), ('managers', 'All Managers'), ('me', 'Only Me')], default='anyone', help_text='Designates who can see this information.', max_length=128, verbose_name='privacy')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculant', to=settings.AUTH_USER_MODEL, verbose_name='Account')),
            ],
            options={
                'verbose_name': 'matriculant',
                'verbose_name_plural': 'matriculants',
            },
        ),
    ]
