# Generated by Django 3.0.6 on 2020-05-20 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet_matriculants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculant',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AddField(
            model_name='matriculant',
            name='trashed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='matriculant',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculant_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
    ]
