# Generated by Django 3.0.6 on 2020-05-16 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet_academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academicyear_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='concentration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='concentration',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concentration_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='concentration',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='courseequalizer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='courseequalizer',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseequalizer_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='courseequalizer',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursegroup_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='courserequisite',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='courserequisite',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courserequisite_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='courserequisite',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursetype_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='coursetype',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculumcourse_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='managementunit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='managementunit',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managementunit_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='managementunit',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schoolyear_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='studentconversion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='studentconversion',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentconversion_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='studentconversion',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='studentconversionitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='studentconversionitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentconversionitem_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='studentconversionitem',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentscore_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
    ]
