# Generated by Django 3.0.6 on 2020-05-15 02:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_academic', '0002_auto_20200508_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentConversion',
            fields=[
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='intranet_academic.Student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Conversion',
                'verbose_name_plural': 'Student Conversions',
            },
        ),
        migrations.CreateModel(
            name='StudentConversionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('ori_code', models.CharField(max_length=128, verbose_name='Origin Code')),
                ('ori_name', models.CharField(max_length=128, verbose_name='Origin Name')),
                ('ori_numeric_score', models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Origin Numeric')),
                ('ori_alphabetic_score', models.CharField(max_length=128, verbose_name='Origin Alphabetic')),
                ('numeric', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Numeric Score')),
                ('alphabetic', models.CharField(max_length=1, verbose_name='Alphabetic Score')),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_items', to='intranet_academic.StudentConversion', verbose_name='Conversion')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_items', to='intranet_academic.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Student Conversion Score',
                'verbose_name_plural': 'Student Conversion Scores',
            },
        ),
    ]
