# Generated by Django 3.0.6 on 2020-05-15 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_academic', '0003_studentconversion_studentconversionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconversion',
            name='ori_institution_name',
            field=models.CharField(default='', max_length=256, verbose_name='Institution Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentconversion',
            name='ori_program_study',
            field=models.CharField(default='', max_length=256, verbose_name='Ori Program Study'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentconversion',
            name='ori_year_of_force',
            field=models.PositiveIntegerField(default=2010, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Institution Name'),
        ),
        migrations.AlterField(
            model_name='studentconversionitem',
            name='numeric',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Numeric Score'),
        ),
    ]
