# Generated by Django 3.0.6 on 2020-05-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_academic', '0003_auto_20200516_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentconversionitem',
            old_name='ori_alphabetic_score',
            new_name='ori_alphabetic',
        ),
        migrations.RenameField(
            model_name='studentconversionitem',
            old_name='ori_numeric_score',
            new_name='ori_numeric',
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='concentration',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='courseequalizer',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='courserequisite',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='managementunit',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='studentconversion',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='studentconversionitem',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
    ]
