# Generated by Django 3.0.6 on 2020-05-15 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_academic', '0004_auto_20200515_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentconversion',
            name='status',
            field=models.CharField(choices=[('DRF', 'Draft'), ('VLD', 'Valid'), ('PST', 'Posted'), ('CNC', 'Cancel')], default='DRF', max_length=128, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='studentconversion',
            name='ori_institution_name',
            field=models.CharField(help_text='Institusi asal', max_length=256, verbose_name='Institution Name'),
        ),
        migrations.AlterField(
            model_name='studentconversion',
            name='ori_program_study',
            field=models.CharField(help_text='Program Studi asal', max_length=256, verbose_name='Program Study'),
        ),
        migrations.AlterField(
            model_name='studentconversion',
            name='ori_year_of_force',
            field=models.PositiveIntegerField(default=2010, help_text='Tahun masuk/angkatan pada institusi asal', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Year of force'),
        ),
    ]
