# Generated by Django 3.0.6 on 2020-05-16 14:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet_academic', '0004_auto_20200516_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_trash', models.BooleanField(default=False, editable=False, verbose_name='trash')),
                ('trashed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('alphabetic', models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('E', 'E')], max_length=2, unique=True, verbose_name='Alphabetic Score')),
                ('numeric', models.DecimalField(decimal_places=0, default=0, max_digits=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Numeric Score')),
                ('min_point', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Numeric Score')),
                ('max_point', models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Numeric Score')),
                ('predicate', models.CharField(max_length=25, unique=True, verbose_name='Alphabetic Score')),
                ('trashed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorerange_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by')),
            ],
            options={
                'verbose_name': 'Score Range',
                'verbose_name_plural': 'Score Ranges',
            },
        ),
    ]
