# Generated by Django 3.0.6 on 2020-05-16 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_academic', '0005_scorerange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerange',
            name='max_point',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Max Point'),
        ),
        migrations.AlterField(
            model_name='scorerange',
            name='min_point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Min Point'),
        ),
        migrations.AlterField(
            model_name='scorerange',
            name='predicate',
            field=models.CharField(max_length=25, unique=True, verbose_name='Predicate'),
        ),
    ]
