# Generated by Django 3.0.6 on 2020-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_academic', '0006_auto_20200516_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorerange',
            name='schema',
            field=models.CharField(choices=[('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], default='D3', max_length=2, verbose_name='Alphabetic Score'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scorerange',
            name='alphabetic',
            field=models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('E', 'E'), ('I', 'I')], max_length=2, verbose_name='Alphabetic Score'),
        ),
        migrations.AlterUniqueTogether(
            name='scorerange',
            unique_together={('schema', 'alphabetic')},
        ),
    ]
