# Generated by Django 3.0.6 on 2020-05-16 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_academic', '0007_auto_20200516_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerange',
            name='max_point',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Max Point'),
        ),
        migrations.AlterField(
            model_name='scorerange',
            name='min_point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Min Point'),
        ),
        migrations.AlterField(
            model_name='scorerange',
            name='numeric',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Numeric Score'),
        ),
        migrations.AlterField(
            model_name='scorerange',
            name='schema',
            field=models.PositiveIntegerField(choices=[(5, 'D3'), (7, 'S1'), (8, 'S2'), (9, 'S3')], default=7, verbose_name='Alphabetic Score'),
        ),
    ]
