# Generated by Django 3.0.6 on 2020-05-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_academic', '0010_auto_20200516_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentconversionitem',
            options={'verbose_name': 'Student Conversion Item', 'verbose_name_plural': 'Student Conversion Items'},
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=False, editable=False, verbose_name='Active'),
        ),
    ]
