# Generated by Django 3.0.6 on 2020-05-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_academic', '0011_auto_20200519_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='is_primary',
        ),
    ]
