# Generated by Django 3.0.6 on 2020-05-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_academic', '0012_remove_curriculum_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, verbose_name='active'),
        ),
    ]
