# Generated by Django 3.0.6 on 2020-05-19 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_academic', '0013_auto_20200519_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AddField(
            model_name='studentscore',
            name='sks',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='sks'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='is_active',
            field=models.BooleanField(default=False, editable=False, verbose_name='active'),
        ),
    ]
