# Generated by Django 3.0.6 on 2020-05-20 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_academic', '0015_studentscore_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscore',
            name='alphabetic',
            field=models.CharField(max_length=1, verbose_name='Alphabetic'),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='numeric',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Numeric'),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='point',
            field=models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='point'),
        ),
    ]
