# Generated by Django 3.0.7 on 2020-06-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_academic', '0016_auto_20200520_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumcourse',
            name='semester_number',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=1, verbose_name='semester'),
        ),
        migrations.AlterField(
            model_name='curriculumcourse',
            name='sks_graduate',
            field=models.PositiveIntegerField(default=0, help_text='Minimum sks graduated to enroll this course', verbose_name='SKS graduate'),
        ),
    ]
