# Generated by Django 3.0.6 on 2020-05-08 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('code', models.CharField(max_length=256, verbose_name='Code')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downlines', to='intranet_employees.Department', verbose_name='Upline')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('note', models.TextField(blank=True, max_length=256, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Employment',
                'verbose_name_plural': 'Employments',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Is Manager')),
                ('is_co_manager', models.BooleanField(default=False, verbose_name='Is Co-Manager')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('employee_required', models.IntegerField(default=1, verbose_name='Employee required')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('department', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staffs', to='intranet_employees.Department', verbose_name='Department')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='intranet_employees.Position', verbose_name='Upline')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('reg_number', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Reg number')),
                ('inner_id', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Inner ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('eid', models.CharField(max_length=128, null=True, verbose_name='Employee ID')),
                ('date_registered', models.DateField(default=django.utils.timezone.now, verbose_name='Date registered')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('tax_id', models.CharField(max_length=128, null=True, verbose_name='Tax ID')),
                ('bank_name', models.CharField(max_length=256, null=True, verbose_name='Bank Name')),
                ('bank_holder_name', models.CharField(max_length=256, null=True, verbose_name='Bank Holder Name')),
                ('bank_account_id', models.CharField(max_length=256, null=True, verbose_name='Bank Account ID')),
                ('account', models.OneToOneField(limit_choices_to={'is_employee': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Account')),
                ('employment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='intranet_employees.Employment', verbose_name='Employment')),
                ('position', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chairmans', to='intranet_employees.Position', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='ExtraPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_positions', to='intranet_employees.Employee', verbose_name='Employee')),
                ('position', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_chairmans', to='intranet_employees.Position', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Chairman',
                'verbose_name_plural': 'Chairmans',
                'unique_together': {('employee', 'position')},
            },
        ),
    ]
