# Generated by Django 3.0.6 on 2020-05-16 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet_employees', '0002_auto_20200516_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='is_deleted',
            new_name='is_trash',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='deleted_at',
            new_name='trashed_at',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='is_deleted',
            new_name='is_trash',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='deleted_at',
            new_name='trashed_at',
        ),
        migrations.RenameField(
            model_name='employment',
            old_name='is_deleted',
            new_name='is_trash',
        ),
        migrations.RenameField(
            model_name='employment',
            old_name='deleted_at',
            new_name='trashed_at',
        ),
        migrations.RenameField(
            model_name='extraposition',
            old_name='is_deleted',
            new_name='is_trash',
        ),
        migrations.RenameField(
            model_name='extraposition',
            old_name='deleted_at',
            new_name='trashed_at',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='is_deleted',
            new_name='is_trash',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='deleted_at',
            new_name='trashed_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='extraposition',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='position',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='department',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='employee',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='employment',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employment_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='extraposition',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extraposition_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='position',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
    ]
