# Generated by Django 3.0.6 on 2020-05-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet_employees', '0003_auto_20200516_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='extraposition',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
    ]
