# Generated by Django 3.0.6 on 2020-05-08 12:30

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('code', models.CharField(max_length=128, verbose_name='Code')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('building', models.CharField(max_length=256, verbose_name='Building')),
                ('capacity', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacity')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
