# Generated by Django 3.0.6 on 2020-05-16 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet_rooms', '0002_auto_20200516_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_deleted',
            new_name='is_trash',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='deleted_at',
            new_name='trashed_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='room',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
    ]
