# Generated by Django 3.0.6 on 2020-05-20 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet_persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AddField(
            model_name='award',
            name='trashed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='award_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='family',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AddField(
            model_name='family',
            name='trashed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='formaleducation',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AddField(
            model_name='formaleducation',
            name='trashed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='formaleducation',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formaleducation_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='nonformaleducation',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AddField(
            model_name='nonformaleducation',
            name='trashed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='nonformaleducation',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nonformaleducation_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AddField(
            model_name='person',
            name='trashed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AddField(
            model_name='publication',
            name='trashed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AddField(
            model_name='skill',
            name='trashed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='trashed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='working',
            name='is_trash',
            field=models.BooleanField(default=False, editable=False, verbose_name='trash'),
        ),
        migrations.AddField(
            model_name='working',
            name='trashed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='working',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
    ]
