# Generated by Django 3.0.6 on 2020-05-16 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet_lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='enrollmentitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollmentitem_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='enrollmentitem',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='lectureschedule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='lectureschedule',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectureschedule_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='lectureschedule',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='lecturescoreweighting',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='lecturescoreweighting',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturescoreweighting_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='lecturescoreweighting',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='lecturestudent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='lecturestudent',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturestudent_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='lecturestudent',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentattendance_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='studentplan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='studentplan',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentplan_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='studentplan',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherattendance_deleter', to=settings.AUTH_USER_MODEL, verbose_name='deleter'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False, verbose_name='is deleted?'),
        ),
    ]
