# Generated by Django 3.0.6 on 2020-05-16 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet_lectures', '0002_auto_20200516_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='is_deleted',
            new_name='is_trash',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='deleted_at',
            new_name='trashed_at',
        ),
        migrations.RenameField(
            model_name='enrollmentitem',
            old_name='is_deleted',
            new_name='is_trash',
        ),
        migrations.RenameField(
            model_name='enrollmentitem',
            old_name='deleted_at',
            new_name='trashed_at',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='is_deleted',
            new_name='is_trash',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='deleted_at',
            new_name='trashed_at',
        ),
        migrations.RenameField(
            model_name='lectureschedule',
            old_name='is_deleted',
            new_name='is_trash',
        ),
        migrations.RenameField(
            model_name='lectureschedule',
            old_name='deleted_at',
            new_name='trashed_at',
        ),
        migrations.RenameField(
            model_name='lecturescoreweighting',
            old_name='is_deleted',
            new_name='is_trash',
        ),
        migrations.RenameField(
            model_name='lecturescoreweighting',
            old_name='deleted_at',
            new_name='trashed_at',
        ),
        migrations.RenameField(
            model_name='lecturestudent',
            old_name='is_deleted',
            new_name='is_trash',
        ),
        migrations.RenameField(
            model_name='lecturestudent',
            old_name='deleted_at',
            new_name='trashed_at',
        ),
        migrations.RenameField(
            model_name='studentattendance',
            old_name='is_deleted',
            new_name='is_trash',
        ),
        migrations.RenameField(
            model_name='studentattendance',
            old_name='deleted_at',
            new_name='trashed_at',
        ),
        migrations.RenameField(
            model_name='studentplan',
            old_name='is_deleted',
            new_name='is_trash',
        ),
        migrations.RenameField(
            model_name='studentplan',
            old_name='deleted_at',
            new_name='trashed_at',
        ),
        migrations.RenameField(
            model_name='teacherattendance',
            old_name='is_deleted',
            new_name='is_trash',
        ),
        migrations.RenameField(
            model_name='teacherattendance',
            old_name='deleted_at',
            new_name='trashed_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='enrollmentitem',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='lectureschedule',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='lecturescoreweighting',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='lecturestudent',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='studentplan',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='enrollmentitem',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollmentitem_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='lectureschedule',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectureschedule_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='lecturescoreweighting',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturescoreweighting_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='lecturestudent',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturestudent_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentattendance_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='studentplan',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentplan_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='trashed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherattendance_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by'),
        ),
    ]
